openapi: 3.0.0
info:
  title: Rental_Store
  description: Allow you to look up & make changes to customers, items & invoices table.
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Local dev server
paths:
  /customer:
    get:
      summary: Retrieves details of all the customers
      responses:
        '200':
          description: list of all the customers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers'
    put:
      summary: Update the customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customers'
      responses:
        '200':
          description: list of all the updated customers
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
        '422':
          description: Missing a field
        '415':
          description: Unsupported media type, the request body should be json
    post:
      summary: Add the customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customers'
      responses:
        '201':
          description: created the list of all the customers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers'
        '400':
          description: Bad Request
        '422':
          description: Missing a field
        '415':
          description: Unsupported media type, the request body should be json
  /customer/{id}:
    get:
      summary: Retrieves details of the customer with the specified id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the customer we arfe looking for
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: show the customer with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers'
        '400':
          description: Bad Request
        '404':
          description: Id not found
    delete:
      summary: Delete all the data related to the customer with the specified id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the customer we are looking for
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: show the customer with the specified id
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Id not found
  /item:
    get:
      summary: Retrieves details of all the items
      responses:
        '200':
          description: list of all the items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Items'
    put:
      summary: Update the items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: list of all the updated items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Items'
        '400':
          description: Bad Request
        '422':
          description: Missing a field
        '415':
          description: Unsupported media type, the request body should be json
    post:
      summary: Add the items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Items'
      responses:
        '201':
          description: created the list of items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Items'
        '400':
          description: Bad Request
        '422':
          description: Missing a field
        '415':
          description: Unsupported media type, the request body should be json
  /item/{id}:
    get:
      summary: Retrieves details of the item with the specified id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the customer we arfe looking for
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: show the item with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Items'
        '400':
          description: Bad Request
        '404':
          description: Id not found
    delete:
      summary: Delete all the data related to the item with the specified id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the item we are looking for
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: show the item with the specified id
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad Request
        '404':
          description: Id not found
  /invoice:
    get:
      summary: Retrieves details of all the invoices along with the customer details, invoice_items
      responses:
        '200':
          description: list of all the invoices
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoices'
    post:
      summary: Add the invoice, add customers & invoice_items if they don't exist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoices'
      responses:
        '201':
          description: created the list of invoices
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoices'
        '400':
          description: Bad Request
        '422':
          description: Missing a field
        '415':
          description: Unsupported media type, the request body should be json
  /invoice/customer/{id}:
    get:
      summary: Retrieves invoices with the specified customer_id
      parameters:
        - name: id
          in: path
          required: true
          description: The customer_id of the invoice we are looking for
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: show the item with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoices'
        '400':
          description: Bad Request
        '404':
          description: Id not found
    delete:
      summary: Delete all the data related to the invoice with the specified customer_id
      parameters:
        - name: id
          in: path
          required: true
          description: The customer_id of the invoice we are looking for
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: show the item with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoices'
        '400':
          description: Bad Request
        '404':
          description: Id not found
  /invoice/{id}:
    delete:
      summary: Delete all the data related to the specified invoice_id
      parameters:
        - name: id
          in: path
          required: true
          description: The invoice_id of the invoice we are looking for
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: show the invoice with the specified invoice_id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoices'
        '400':
          description: Bad Request
        '404':
          description: Id not found

components:
  schemas:
    Customers:
      type: array
      items:
        type: object
        properties:
          customerId:
            type: integer
          firstName:
            type: string
          lastName:
            type: string
          email:
            type: string
          company:
            type: string
          phone:
            type: string
          invoiceList:
            type: array
            items:
              type: object
              properties:
                invoiceId:
                  type: integer
                customerId:
                  type: integer
                _orderDate:
                  type: string
                _pickupDate:
                  type: string
                _returnDate:
                  type: string
                lateFee:
                  type: number
        required:
          - firstName
          - lastName
          - email
          - company
          - phone
    Items:
      type: array
      items:
        type: object
        properties:
          itemId:
            type: integer
          name:
            type: string
          description:
            type: string
          dailyRate:
            type: number
        required:
          - name
          - dailyRate
    Invoices:
      type: array
      items:
        type: object
        properties:
          invoiceId:
            type: integer
          customer:
            type: object
            properties:
              customerId:
                type: integer
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              company:
                type: string
              phone:
                type: string
          _orderDate:
            type: string
          _pickupDate:
            type: string
          _returnDate:
            type: string
          lateFee:
            type: number
          invoiceItemList:
            type: array
            items:
              type: object
              properties:
                invoiceItemId:
                  type: integer
                item:
                  type: object
                  properties:
                    itemId:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
                    dailyRate:
                      type: number
                quantity:
                  type: integer
                unitRate:
                  type: number
                discount:
                  type: number
        required:
          - customer
          - orderDate
          - pickupDate
          - returnDate
          - lateFee
          - invoiceItems